# Generated by Django 2.0 on 2018-01-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickynote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('shared', models.BooleanField()),
                ('canBeDeleted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickynote.Colour')),
            ],
        ),
        migrations.AddField(
            model_name='stickynote',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stickynote.StickyGroup'),
        ),
    ]
