# Generated by Django 2.0 on 2018-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0002_auto_20180104_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickygroup',
            name='canBeDeleted',
        ),
        migrations.AddField(
            model_name='stickygroup',
            name='cannotBeDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
