# Generated by Django 2.0 on 2018-01-10 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickynote', '0004_auto_20180104_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sticky_Collaboraters',
            new_name='Collaborator',
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RemoveField(
            model_name='stickygroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='group',
        ),
        migrations.AddField(
            model_name='colour',
            name='filename',
            field=models.CharField(default='stickynote_yellow.png', max_length=40),
        ),
        migrations.DeleteModel(
            name='StickyGroup',
        ),
    ]
