# Generated by Django 2.0 on 2018-01-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0006_auto_20180110_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='author',
        ),
    ]
