# Generated by Django 2.0 on 2018-01-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0007_remove_stickynote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='stickynote',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
