# Generated by Django 2.0 on 2018-01-13 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friended_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 19, 18, 39, 941499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 19, 18, 39, 942502, tzinfo=utc)),
        ),
    ]
