# Generated by Django 2.0 on 2018-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20180113_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friended_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
